import { useCallback, useEffect, useState } from 'react';
import BoardMemoryMatch from '@/games/boardMemoryMatch/BoardMemoryMatch';
import type { Difficulty } from '@/games/boardMemoryMatch/gameLogic';
import GamePageLayout from '@/components/GamePageLayout'; import GameHeader from '@/components/GameHeader'; import ScoreBox from '@/components/ScoreBox'; import DifficultyPills from '@/components/DifficultyPills'; import HowToPlayPanel from '@/components/HowToPlayPanel'; import WinOverlay from '@/components/WinOverlay'; import { useLocalStorage } from '@/hooks/useLocalStorage';
const options: { value: Difficulty; label: string }[] = [{ value: 'easy', label: 'Easy · 4×4' }, { value: 'medium', label: 'Medium · 6×4' }, { value: 'hard', label: 'Hard · 6×6' }];
export default function GameMemoryMatch() {
  const [difficulty,setDifficulty]=useState<Difficulty>('easy'), [moves,setMoves]=useState(0), [time,setTime]=useState(0), [won,setWon]=useState(false), [resetKey,setResetKey]=useState(0);
  const easyTime=useLocalStorage('pixelplay-memory-match-best-time-easy',0), mediumTime=useLocalStorage('pixelplay-memory-match-best-time-medium',0), hardTime=useLocalStorage('pixelplay-memory-match-best-time-hard',0); const easyMoves=useLocalStorage('pixelplay-memory-match-best-moves-easy',0), mediumMoves=useLocalStorage('pixelplay-memory-match-best-moves-medium',0), hardMoves=useLocalStorage('pixelplay-memory-match-best-moves-hard',0); const [bestTime,setBestTime]={easy:easyTime,medium:mediumTime,hard:hardTime}[difficulty], [bestMoves,setBestMoves]={easy:easyMoves,medium:mediumMoves,hard:hardMoves}[difficulty];
  useEffect(() => { if (won) return; const id=setInterval(()=>setTime(t=>t+1),1000); return()=>clearInterval(id); },[won,resetKey,difficulty]);
  const reset=useCallback((next=difficulty)=>{setDifficulty(next);setMoves(0);setTime(0);setWon(false);setResetKey(k=>k+1);},[difficulty]);
  const win=useCallback(()=>{setWon(true);setBestTime(b=>!b||time<b?time:b);setBestMoves(b=>!b||moves+1<b?moves+1:b);},[moves,time,setBestMoves,setBestTime]);
  return <GamePageLayout><GameHeader title="Memory Match" color="#8ABAC5"><ScoreBox label="Moves" value={moves} bgColor="#8ABAC5"/><ScoreBox label="Time" value={time} bgColor="#FFF"/></GameHeader><DifficultyPills options={options} value={difficulty} onChange={reset} color="#8ABAC5"/><div className="relative mt-5"><BoardMemoryMatch key={`${difficulty}-${resetKey}`} difficulty={difficulty} onMove={()=>setMoves(m=>m+1)} onWin={win} resetKey={resetKey}/>{won&&<WinOverlay title={`Matched in ${moves} moves!`} color="#8ABAC5" onKeepGoing={()=>setWon(false)} onNewGame={()=>reset()}/>}</div><p className="text-center font-body text-sm mt-3 text-muted-foreground">Best: {bestMoves||'—'} moves · {bestTime||'—'} seconds</p><HowToPlayPanel instructions="Flip two cards at a time and remember their symbols. Matching pairs stay visible; clear the board in as few moves and seconds as possible. Use arrow keys plus Enter or Space, or tap a card."/></GamePageLayout>;
}
